import { MongoClient } from "mongodb";
const base = process.env.MONGODB_URI_BASE || "mongodb://localhost:27017";
const c = new MongoClient(base);
await c.connect();
const db = c.db("filanex_montiel");
const muestra = await db.collection("clientes").find({}).limit(5).project({ nombre: 1, nombreComercial: 1, creado: 1, createdAt: 1, email: 1 }).toArray();
console.log("CLIENTES:", JSON.stringify(muestra, null, 1));
const audit = await db.collection("auditoria").find({}).sort({ _id: 1 }).limit(6).toArray();
console.log("AUDIT_PRIMERAS:", JSON.stringify(audit.map(a => ({ fecha: a.fecha, accion: a.accion, usuario: a.usuario, entidad: a.entidad })), null, 1));
const auditU = await db.collection("auditoria").find({}).sort({ _id: -1 }).limit(4).toArray();
console.log("AUDIT_ULTIMAS:", JSON.stringify(auditU.map(a => ({ fecha: a.fecha, accion: a.accion, usuario: a.usuario, entidad: a.entidad })), null, 1));
await c.close();
